# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
android.useAndroidX=true
android.enableR8.fullMode=false
android.injected.androidTest.leaveApksInstalledAfterRun=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL,LIBRARY_CONSTRAINTS_SHOULD_BE_DISABLED
